src/main/java/je/backit/entity/Campaign.java
package je.backit.entity;

import java.math.BigDecimal;
import java.text.NumberFormat;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import static java.util.Collections.emptyList;
import java.util.List;
import java.util.Locale;
import je.backit.jooq.tables.records.RewardRecord;
import je.backit.utils.TimeLeft;

public class Campaign extends BaseEntity {

  private Integer id;
  private String title;
  private String summary;
  private String description;
  private List<String> categories;
  private String hashtag;
  private String videoURI;
  private String imageURI;
  private String type;
  private ZonedDateTime startDate;
  private ZonedDateTime endDate;
  private BigDecimal targetFunding;

  private String timeRemaining;
  private BigDecimal backed;
  private Integer noBackers;
  private BigDecimal pledged;
  private Integer percentageFunded;

  private String formatedEndDate;

  private List<RewardRecord> rewards;



  public Integer getPercentageFunded() {
    return percentageFunded;
  }


  public void setPercentageFunded(Integer amount) {
    this.percentageFunded = amount;
  }

  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public BigDecimal getTargetFunding() {
    return targetFunding;
  }

  public String getTargetFundingAsString() {
    return formatAsPounds(targetFunding);
  }

  private String formatAsPounds(BigDecimal amount) {
    return NumberFormat.getNumberInstance(Locale.UK).format(amount);
  }

  public void setTargetFunding(BigDecimal targetFunding) {
    this.targetFunding = targetFunding;
  }

  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getSummary() {
    return summary;
  }

  public void setSummary(String summary) {
    this.summary = summary;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public List<String> getCategories() {
    return categories == null ? emptyList() : categories;
  }

  public void setCategories(List<String> categories) {
    this.categories = categories;
  }

  public String getHashtag() {
    return hashtag;
  }

  public void setHashtag(String hashtag) {
    this.hashtag = hashtag;
  }

  public String getVideoURI() {
    return videoURI;
  }

  public void setVideoURI(String videoURI) {
    this.videoURI = videoURI;
  }

  public String getImageURI() {
    return imageURI;
  }

  public void setImageURI(String imageURI) {
    this.imageURI = imageURI;
  }

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public void setStartDate(ZonedDateTime startDate) {
    this.startDate = startDate;
  }

  public void setEndDate(ZonedDateTime endDate) {
    this.endDate = endDate;
  }

  public ZonedDateTime getStartDate() {
    return startDate;
  }

  public ZonedDateTime getEndDate() {
    return endDate;
  }

  public String getFormatedEndDate() {
    DateTimeFormatter format = DateTimeFormatter.ofPattern("MMM d yyyy  hh:mm a");
    return endDate.format(format);
  }




  public String getTimeRemaining() {
    return timeRemaining;
  }

  public void setTimeRemaining(String timeRemaining) {
    this.timeRemaining = timeRemaining;
  }

  public BigDecimal getBacked() {
    return backed;
  }

  public void setBacked(BigDecimal backed) {
    this.backed = backed;
  }

  public Integer getNoBackers() {
    return noBackers;
  }

  public void setNoBackers(Integer noBackers) {
    this.noBackers = noBackers;
  }


  public TimeLeft getTimeLeft() {
    return new TimeLeft(ZonedDateTime.now(), endDate);
  }

  public List<RewardRecord> getRewards() {
    return rewards == null ? emptyList() : rewards;
  }

  public void setRewards(List<RewardRecord> rewards) {
    this.rewards = rewards;
  }

  public BigDecimal getPledged() {
    return pledged;
  }

  public String getPledgedAsString() {
    return formatAsPounds(pledged);
  }

  public void setPledged(BigDecimal pledged) {
    this.pledged = pledged;
  }




}

src/main/java/je/backit/boundary/LoginController.java
package je.backit.boundary;

import java.io.IOException;
import javax.inject.Inject;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import je.backit.control.AccountDAO;
import je.backit.entity.Account;


@WebServlet("/LoginController")
public class LoginController extends HttpServlet {
	private static final long serialVersionUID = 1L;

  @Inject AccountDAO accountDAO;

	public LoginController() {
		super();
	}

	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		String username = request.getParameter("username");
		String password = request.getParameter("password");
		RequestDispatcher rd = null;

		if (accountDAO.authenticate(username, password)) {
			rd = request.getRequestDispatcher("/success.jsp");
			Account user = accountDAO.findByUsername(username);
			request.setAttribute("user", user);
		} else {
			rd = request.getRequestDispatcher("/error.jsp");
		}
		rd.forward(request, response);
	}

}

src/main/webapp/WEB-INF/jsp/GetBacking.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if (IE 7)&!(IEMobile)]><html class="no-js lt-ie9 lt-ie8" lang="en"><![endif]-->
<!--[if (IE 8)&!(IEMobile)]><html class="no-js lt-ie9" lang="en"><![endif]-->
<!--[if (IE 9)]><html class="no-js ie9" lang="en"><![endif]-->
<!--[if gt IE 8]><!-->
<html lang="en-GB"> <!--<![endif]-->

    <jsp:include page="head.jsp"/>

<body>
<jsp:include page="header.jsp"/>



        <!-- contact Section -->
        <article style="margin-top: 50px;" class="section gray-bg">
            <section id="contact">
                <!-- Title Page -->
                <div class="section-title">
                    <h1 class="title">Get Backing<span>.</span></h1>
                </div>

                <div class="contact-form-full">


                    <form id="contact-form" class="contact-form" action="php/contact.php">
                        <p class="contact-name">
                            <label>Project name:</label>
                            <input id="contact_name" type="text" placeholder="Type your name here..." value="" name="name"/>
                        </p>

                        <p class="contact-message">
                            <label>Project Summary:</label>
                            <textarea id="contact_message" placeholder="Type your message here..." name="message" rows="15" cols="40"></textarea>
                        </p>

                        <p class="contact-message">
                            <label>Project Description:</label>
                            <textarea id="contact_message" placeholder="Type your message here..." name="message" rows="15" cols="40"></textarea>
                        </p>

                        <p>
                            <label>Choose a category:</label>
                            <select name="Category">
                            <option value="Milk">Art</option>
                            <option value="Cheese">Music</option>
                            <option value="Bread">Sport</option>
                        </p>

                        <p class="contact-email">
                            <label>Your hashtag:</label>
                            <input id="contact_email" type="text" placeholder="Type your hashtag here..." value="" name="email"/>
                        </p>

                        <p>
                            <label>Upload your video:</label>
                            <input type="text" name="textline" size="30">
                        </p>
                            <label>Upload your video:</label>
                            <input type="file" name="datafile" size="40">
                        </p>

                        <p>
                            <label>Upload your Ppoto:</label>
                            <input type="text" name="textline" size="30">
                        </p>
                            <label>Upload your photo:</label>
                            <input type="file" name="datafile" size="40">
                        </p>

                        <p>
                            <label>Choose a campaign model:</label>
                            <select name="model">
                            <option value="Milk">Art</option>
                            <option value="Cheese">Music</option>
                            <option value="Bread">Sport</option>
                        </p>

                        <p class="contact-email">
                            <label>Your start date:</label>
                            <input id="contact_email" type="text" placeholder="Type your start date here..." value="" name="email"/>
                        </p>

                        <p class="contact-email">
                            <label>Your end date:</label>
                            <input id="contact_email" type="text" placeholder="Type your end date here..." value="" name="email"/>
                        </p>

                        <p class="contact-email">
                            <label>Amount of backing:</label>
                            <input id="contact_email" type="text" placeholder="Type your target amount here..." value="" name="email"/>
                        </p>

                        <p class="contact-submit">
                            <a id="contact-submit" class="submit" type="submit" value="submit">Submit your details</a>
                        </p>



        
                        
                        <div id="response">
                        
                        </div>
                    </form>                        
                </div>
                <!-- End Title Page -->

                <div class="contact-details">
                    <h1>Looking forward to getting backing?</h1>
                <ul>

                    <li><a href="mailto:hello@backit.je">hello@backit.je</a></li>
         
                </ul>
            </div>
            </section>
        </article>
        <!-- contact Section -->

<jsp:include page="footer.jsp"/>

       <script src="${pageContext.request.contextPath}/js/main-vendors.js"></script>
        <script src="${pageContext.request.contextPath}/js/main.js"></script>

</body>
</html>

src/main/webapp/WEB-INF/jsp/ShowCampaignsList.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if (IE 7)&!(IEMobile)]><html class="no-js lt-ie9 lt-ie8" lang="en"><![endif]-->
<!--[if (IE 8)&!(IEMobile)]><html class="no-js lt-ie9" lang="en"><![endif]-->
<!--[if (IE 9)]><html class="no-js ie9" lang="en"><![endif]-->
<!--[if gt IE 8]><!-->
<html lang="en-GB"> <!--<![endif]-->

    <jsp:include page="head.jsp"/>

<body>
<jsp:include page="header.jsp"/>

     <div style="margin-top:30px;" class="section"><img src="${pageContext.request.contextPath}/img/logo.svg"></div>

        <!-- Home Section -->
        <article class="section gray-bg">
            <section id="how-it-works">
                <!-- Title Page -->
                <div class="section-title">

                <h1 class="title" style="font-size:57px">The crowdfunding platform for Jersey!</h1>

                <br><br>

<p class="title-description">BackIt connects great projects in our community with people who are passionate about good causes.
 Crowdfunding pulls multiple individual donations together to achieve big things. You may have heard people say, 'they only need a few pounds for a group of people and it's done', well that's what crowdfunding is.</p>



<p class="title-description">By keeping it local, your donation can achieve big things here in Jersey. You can back a variety of projects from art, music, heritage and sport.</p>



<p class="title-description">Make a difference - BackIt today!</p>



                </div>
                <!-- End Title Page -->
            </section>
        </article>
        <!-- Home Section -->

        <!-- Project Section -->

        <article id="current-projects" class="section white-bg">
            <section class="listings">
              	<c:forEach items="${campaigns}" var="campaign">
                <div class="campaign-listing">
                    <a href="${pageContext.request.contextPath}/v1/campaigns/details/?campaignId=${campaign.id}"><img src="${pageContext.request.contextPath}/img/${campaign.imageURI}" alt=""></a>
                    <h3><a href="${pageContext.request.contextPath}/v1/campaigns/details/?campaignId=${campaign.id}">${campaign.title}</a></h3>
                    <p><a href="${pageContext.request.contextPath}/v1/campaigns/details/?campaignId=${campaign.id}">${campaign.summary}</a></p>


<%--             <c:if test="${empty campaign.timeLeft.timeLeftAsString}">                            --%>
<%-- 		            <c:choose> --%>
<%-- 		        			<c:when test="${campaign.percentageFunded < 100}">		        			 --%>
<!-- 		        				<div class="campaign-funding failed">	       			 -->
<%-- 		        			</c:when> --%>
<%-- 		       		 		<c:when test="${campaign.percentageFunded >= 100}"> --%>
<!-- 		       		 			<div class="campaign-funding successful"> -->
<%-- 		       		 		</c:when> --%>
<%-- 					</c:choose> --%>
<%--             </c:if> --%>

<%--                    <c:if test="${campaign.timeLeft.timeLeftAsString != 0}">                            --%>

               <div class="campaign-funding">
<%--                         </c:if> --%>



                            <progress value="${campaign.percentageFunded}" max="100"></progress>

                        <ul>
                            <li><strong>&pound;&nbsp;${campaign.targetFundingAsString}</strong> <span>Target</span></li>


                            <li
                            	<c:if test ="${campaign.timeLeft.unitAsString == \"hours left\" }" var="var_name" scope= "page" >
                            		class="ends-today"
                            	</c:if>
                            ><strong>${campaign.timeLeft.timeLeftAsString}</strong> <span>${campaign.timeLeft.unitAsString}</span></li>



                            <li><strong>${campaign.percentageFunded}%</strong> <span>Backed</span></li>
                            <li><strong>${campaign.noBackers}</strong> <span>Backers</span></li>
                        </ul>
                    </div>
                </div>
                </c:forEach>

            </section>
        </article>
                <!-- Project Section -->



        <!-- contact Section -->
        <article class="section gray-bg">
            <section id="contact">
                <!-- Title Page -->
                <div class="section-title">
                    <h1 class="title">Contact <img style="height: auto; position: relative; top: 10px; width: 200px;" src="${pageContext.request.contextPath}/img/logo.svg"></h1>
                </div>

                <div class="contact-form-full">


                    <form id="contact-form" class="contact-form" action="php/contact.php">
                        <p class="contact-name">
                            <label>Full name:</label>
                            <input id="contact_name" type="text" placeholder="Type your name here..." value="" name="name"/>
                        </p>
                        <p class="contact-email">
                            <label>Email address:</label>
                            <input id="contact_email" type="text" placeholder="Type your email here..." value="" name="email"/>
                        </p>
                        <p class="contact-message">
                            <label>Message:</label>
                            <textarea id="contact_message" placeholder="Type your message here..." name="message" rows="5" cols="40"></textarea>
                        </p>
                        <p class="contact-submit">
                            <a id="contact-submit" class="submit" type="submit" value="submit">Send Your Email</a>
                        </p>

                        <div id="response">

                        </div>
                    </form>
                </div>
                <!-- End Title Page -->

                <div class="contact-details">
                    <h1>Feel free to get in touch with us</h1>
                <ul>

                    <li><a href="mailto:hello@backit.je">hello@backit.je</a></li>

                </ul>
            </div>
            </section>
        </article>
        <!-- contact Section -->


<jsp:include page="footer.jsp"/>

       <script src="${pageContext.request.contextPath}/js/main-vendors.js"></script>
        <script src="${pageContext.request.contextPath}/js/main.js"></script>

</body>
</html>

src/main/webapp/WEB-INF/jsp/error.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>Login failed, please try again.

</body>
</html>

src/main/webapp/WEB-INF/jsp/footer.jsp
 <footer class="section">
            <section id="footer">
                <p class="credits">&copy; 2015 BackIt.je</p>

                <div id="social-area-pages">
                    <nav id="social-pages">
                        <ul>
                            <li><a href="https://twitter.com/" title="Follow us on Twitter" target="_blank"><span class="fa fa-twitter"></span></a></li>
                            <li><a href="https://www.facebook.com/" title="Follow us on Facebook" target="_blank"><span class="fa fa-facebook"></span></a></li>
                            <li><a href=" https://www.youtube.com/" title="Follow us on YouTube" target="_blank"><span class="fa fa-youtube"></span></a></li>
                            <li><a href="http://www.instagram.com/" title="Follow us on Instagram" target="_blank"><span class="fa fa-instagram"></span></a></li>
                        </ul>
                    </nav>
                </div>
            </section>
        </footer>

src/main/webapp/WEB-INF/jsp/head.jsp
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>BackIt.je | The Jersey Crowdfunding Platform</title>

        <meta name="description" content="BackIt.je - A crowdfunding platform for Jersey specific civic, community, creative and commerce projects, featuring a choice of campaign types including thresholds, subscriptions and donations.">
        <meta name="keywords" content="jersey, crowdfunding, fund-raising">
        <meta name="robots" content="index, follow">

        <meta name="viewport" content="width=device-width, initial-scale=1.0 user-scalable=no">
        <meta name="HandheldFriendly" content="true">
        <meta name="MobileOptimized" content="320">
        <meta name="theme-color" content="#fff">
        <!--[if IEMobile]><meta http-equiv="cleartype" content="on"><![endif]-->

        <link href="${pageContext.request.contextPath}/css/main.css" rel="stylesheet">
        <link rel="shortcut icon" href="${pageContext.request.contextPath}/ico/favicon.ico">
        <link rel="apple-touch-icon" href="${pageContext.request.contextPath}/ico/apple-touch-icon-57-precomposed.png">
        <link rel="apple-touch-icon" sizes="114x114" href="${pageContext.request.contextPath}/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon" sizes="72x72" href="${pageContext.request.contextPath}/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon" sizes="144x144" href="${pageContext.request.contextPath}/ico/apple-touch-icon-144-precomposed.png">


		<style>
		@import url(http://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,300italic,300,700,700italic);

@font-face {
    font-family: 'museo_slab500';
    src: url('${pageContext.request.contextPath}/fonts/Museo_Slab_500_2-webfont.eot');
    src: url('${pageContext.request.contextPath}/fonts/Museo_Slab_500_2-webfont.eot?#iefix') format('embedded-opentype'),
         url('${pageContext.request.contextPath}/fonts/Museo_Slab_500_2-webfont.woff2') format('woff2'),
         url('${pageContext.request.contextPath}/fonts/Museo_Slab_500_2-webfont.woff') format('woff'),
         url('${pageContext.request.contextPath}/fonts/Museo_Slab_500_2-webfont.ttf') format('truetype'),
         url('${pageContext.request.contextPath}/fonts/Museo_Slab_500_2-webfont.svg#museo_slab500') format('svg');
    font-weight: normal;
    font-style: normal;
}

@font-face {
  font-family: 'FontAwesome';
  src: url('{pageContext.request.contextPath}/fonts/font-awesome/fontawesome-webfont.eot');
  src: url('{pageContext.request.contextPath}/fonts/font-awesome/fontawesome-webfont.eot') format('embedded-opentype'), 
  url('{pageContext.request.contextPath}/fonts/font-awesome/fontawesome-webfont.woff2') format('woff2'),
   url('{pageContext.request.contextPath}/fonts/font-awesome/fontawesome-webfont.woff') format('woff'),
   url('{pageContext.request.contextPath}/fonts/font-awesome/fontawesome-webfont.ttf') format('truetype'), 
   url('{pageContext.request.contextPath}/fonts/font-awesome/fontawesome-webfont.svg') format('svg');
  font-weight: normal;
  font-style: normal;
}
</style>
 <link href="${pageContext.request.contextPath}/css/font-awesome.css" rel="stylesheet">
		
		
		
		
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
          ga('create', 'UA-60756207-1', 'auto');
          ga('send', 'pageview');
        </script>
    
    </head>

src/main/webapp/WEB-INF/jsp/header.jsp
        <!-- Header-->
        <header>

            <div id="logo">
                    <a href="${pageContext.request.contextPath}/v1/campaigns/list/" style="background:url(${pageContext.request.contextPath}/img/logo.svg) no-repeat" title="BackIt.je">BackIt.je</a>
            </div>


            <!-- Navbar-->
            <nav id='cssmenu'>
               <ul id="nav">
                  <li class="current"><a href="${pageContext.request.contextPath}/v1/campaigns/list/">How it works</a></li>
                    <li><a href="${pageContext.request.contextPath}/v1/campaigns/list/#current-projects">Projects</a></li>
                    <li><a href="${pageContext.request.contextPath}/v1/campaigns/backing/">Get backing</a></li>
                    <li><a href="${pageContext.request.contextPath}/v1/campaigns/list/#contact">Contact</a></li>
                    <li><a href="${pageContext.request.contextPath}/v1/Login">Log In</a></li>
               </ul>
            </nav>
            <!-- End navbar-->
            
           
        </header>
        <!-- End header-->

src/main/webapp/WEB-INF/jsp/login.jsp
<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if (IE 7)&!(IEMobile)]><html class="no-js lt-ie9 lt-ie8" lang="en"><![endif]-->
<!--[if (IE 8)&!(IEMobile)]><html class="no-js lt-ie9" lang="en"><![endif]-->
<!--[if (IE 9)]><html class="no-js ie9" lang="en"><![endif]-->
<!--[if gt IE 8]><!-->
<html lang="en-GB"> <!--<![endif]-->

  <jsp:include page="head.jsp"/>
  
    <body>

<jsp:include page="header.jsp"/>

		<div class="login-content">
			<div id="login" class="login-content-inner">
				<form method="post" action="${pageContext.request.contextPath}/v1/campaigns/list/">
					<h2>Log In</h2>
			        <p><input type="text" name="login" value="" placeholder="Username or Email"></p>
			        
			        <p><input type="password" name="password" value="" placeholder="Password"></p>

			        <p class="remember_me">
			          <label>
			            <input id="log-in-different" type="checkbox" name="remember_me" id="remember_me">
			            Remember me on this computer
			          </label>
			        </p>
			        <p><button type="submit" class="button">Login</button></p>
		      	</form>
		    </div>
	    </div><!-- End login-content -->

<jsp:include page="footer.jsp"/>

       <script src="${pageContext.request.contextPath}/js/main-vendors.js"></script>
        <script src="${pageContext.request.contextPath}/js/main.js"></script>

</body>
</html>

src/main/webapp/WEB-INF/jsp/success.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix ="c" %>
<title>Insert title here</title>
</head>
<body>Welcome ${requestScope['user'].username}.

</body>
</html>